// app/layout.tsx (Server Component)
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import RootLayout from "@/app/RootLayout";

export default function Layout({ children }: Readonly<{ children: React.ReactNode }>) {
  return <RootLayout>{children}</RootLayout>;
}
