import type { Metadata } from "next";

import { Navbar } from "@/components/user/Layout/Navbar";
import Footer  from "@/components/user/Layout/Footer";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
 
     <>  

     
            < Navbar />
          
          {children}
          < Footer />
      
        
          </>
  

  );
}
